services:
  shareapp:
    build: .
    container_name: shareapp
    restart: unless-stopped
    volumes:
      - goshare-appdata-data:/data
    labels:
      - "traefik.http.routers.shareapp.rule=Host(`share.app.n2h.me`)"
      - "traefik.http.services.shareapp.loadbalancer.server.port=8080"
    networks:
      - proxy-tier

volumes:
  goshare-appdata:

networks:
  proxy-tier:
    external: true
