services:
  shareapp:
    build: .
    container_name: shareapp
    restart: unless-stopped
    volumes:
      - goshare-appdata:/data
    labels:
      - "dnsweaver.hostname=share.apps.n2h.me"
    networks:
      - proxy-tier

volumes:
  goshare-appdata:

networks:
  proxy-tier:
    external: true
